=== Avinna10/Gift-Store/catalog_20048839.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Root Element-->
    <xs:element name="Avinna_Store">
        <xs:complexType>
            <xs:sequence>
                <!-- CHild Elements of root element-->
                <xs:element ref="store" />
                <xs:element ref="branch" minOccurs="1" maxOccurs="unbounded" />
                <xs:element ref="contact_details" />
                <xs:element ref="footer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Tags related to store element-->
    <xs:element name="store">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="top" />
                <xs:element ref="nav" />
            </xs:sequence>
            <xs:attribute ref="id" use="required" fixed="1001" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="id" type="xs:positiveInteger" />

    <!-- Tags of element top-->
    <xs:element name="top">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="left" />
                <xs:element ref="right" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Tags of complex type element left-->
    <xs:element name="left">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="logo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Tag of empty element logo-->
    <xs:element name="logo" />

    <!-- Tags of complex element right-->
    <xs:element name="right">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" />
                <xs:element ref="note" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Tags of complex element type-->
    <xs:element name="name">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="store_type" use="required" fixed="physical" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="store_type" type="xs:string" />

    <!-- Tags of simple type element note-->
    <xs:element name="note" type="xs:string" />

    <!-- Tags related to complex type element nav-->
    <xs:element name="nav">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="home" />
                <xs:element ref="cards" />
                <xs:element ref="contact_us" />
                <xs:element ref="search" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Child elements of nav-->
    <xs:element name="home" type="xs:string" />
    <xs:element name="cards" type="xs:string" />
    <xs:element name="contact_us" type="xs:string" />
    <xs:element name="search" type="xs:string" />

    <!-- Start of tags for the element branch-->
    <xs:element name="branch">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="branch_detail" maxOccurs="1" />
                <xs:element ref="voucher" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute ref="branch_id" use="required"/>
            <xs:attribute ref="open" use="optional" default="8hr/day"/>
        </xs:complexType>
    </xs:element>

    <!-- Tags for attributes of branch-->
    <xs:attribute name="branch_id">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="[A-Z][0-9]{5}[A-Z]" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="open" type="xs:string" />

    <!-- Tags of complex type element branch-->
    <xs:element name="branch_detail">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="branch_name" />
                <xs:element ref="branch_address" />
                <xs:element ref="branch_contact" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Restriction on element branch_name-->
    <xs:element name="branch_name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="Branch [A-Z]"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="branch_address" type="xs:string" />

    <!-- Complex Type Element-->
    <xs:element name="branch_contact">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mobile_no" />
                <xs:element ref="toll_free" minOccurs="0" maxOccurs="1" />
                <xs:element ref="branch_email" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Simple Type Elements-->
    <xs:element name="mobile_no" type="xs:string" />
    <xs:element name="toll_free" type="xs:string" />
    <xs:element name="branch_email" type="xs:string" />

    <!-- Complex Type Element-->
    <xs:element name="voucher">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gift_vouchers" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Complex Type Element-->
    <xs:element name="gift_vouchers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="buy" />
                <xs:element ref="buy_txt"/>
                <xs:element ref="voucher_image" />
                <xs:element ref="voucher_name" />
                <xs:element ref="redeem_amount" />
                <xs:element ref="edition" minOccurs="0" maxOccurs="1" />
                <xs:element ref="table" />
            </xs:sequence>
            <xs:attribute ref="voucher_id" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Empty Element-->
    <xs:element name="buy" />

    <xs:element name="buy_txt" type="xs:string" />

    <xs:element name="voucher_image">
        <xs:complexType>
            <xs:attribute ref="image_id" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Use of Restriction (pattern)-->
    <xs:attribute name="image_id">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="spotify|adidas|amazon|walmart|argos|scp" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="voucher_name">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="serial_no" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Use of restriction (pattern)-->
    <xs:attribute name="voucher_id">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="ID[0-9]{4}[a-z][A-Z][0-9]" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <!-- Use of restriction (length)-->
    <xs:attribute name="serial_no">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:length value="10" /> 
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="redeem_amount" type="xs:string" />

    <!-- Use of restriction (enumeration)-->
    <xs:element name="edition">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Limited Edition" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="table_row" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Child elements of elemenet table_row-->
    <xs:element name="table_row">
        <xs:complexType>
            <xs:all>
                <xs:element ref="company_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="type_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="company" minOccurs="0" maxOccurs="1" />
                <xs:element ref="voucher_type" minOccurs="0" maxOccurs="1" />
                <xs:element ref="rating_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="valid_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="voucher_rating" minOccurs="0" maxOccurs="1" />
                <xs:element ref="rating_icon" minOccurs="0" maxOccurs="1" />
                <xs:element ref="voucher_validity" minOccurs="0" maxOccurs="1" />
                <xs:element ref="delivery_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="return_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="delivery" minOccurs="0" maxOccurs="1" />
                <xs:element ref="return_policy" minOccurs="0" maxOccurs="1" />
                <xs:element ref="cost_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="voucher_cost" minOccurs="0" maxOccurs="1" />
                <xs:element ref="discount" minOccurs="0" maxOccurs="1" />
                <xs:element ref="total_price" minOccurs="0" maxOccurs="1" />
                <xs:element ref="description_txt" minOccurs="0" maxOccurs="1" />
                <xs:element ref="description" minOccurs="0" maxOccurs="1" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="company_txt" type="xs:string" />

    <xs:element name="type_txt" type="xs:string" />

    <!-- Complex Type Element-->
    <xs:element name="company">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="reviewCompany">
                    <xs:attribute ref="platform" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <!-- Applying restriction for company element-->
    <xs:simpleType name="reviewCompany">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Spotify" />
            <xs:enumeration value="Walmart" />
            <xs:enumeration value="Argos" />
            <xs:enumeration value="Amazon" />
            <xs:enumeration value="Adidas" />
            <xs:enumeration value="SCP" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Use of restriction (pattern)-->
    <xs:attribute name="platform">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="online|shop" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="voucher_type">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="reviewType">
                    <xs:attribute ref="code_no" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Use of restriction (pattern)-->
    <xs:simpleType name="reviewType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Physical|Digital" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Use of restriction (pattern)-->
    <xs:attribute name="code_no">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{2}[A-Z]{2}" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="rating_txt" type="xs:string" />
    <xs:element name="valid_txt" type="xs:string" />

    <!-- Use of restriction (max and min Inclusive)-->
    <xs:element name="voucher_rating">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="1" />
                <xs:maxInclusive value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- Empty Element-->
    <xs:element name="rating_icon" />

    <xs:element name="voucher_validity">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="valid" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Use of restriction (enumeration)-->
    <xs:attribute name="valid">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="national" />
                <xs:enumeration value="international" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="delivery_txt" type="xs:string" />
    <xs:element name="return_txt" type="xs:string" />

    <!-- Complex Type Element-->
    <xs:element name="delivery">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="delivery_type" use="required"/>
                    <xs:attribute ref="charge" use="optional" fixed="2"/>   <!-- value of charge must be 2-->
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Use of restriction (enumeration)-->
    <xs:attribute name="delivery_type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="online" />
                <xs:enumeration value="home_delivery" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="charge" type="xs:positiveInteger" />

    <xs:element name="return_policy">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="return_duration" minOccurs="0" maxOccurs="1" />    <!-- represents optional element-->
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="return_duration" type="xs:string" />

    <xs:element name="cost_txt"></xs:element>

    <xs:element name="voucher_cost">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="discount_id" use="optional" fixed="discounted" />    <!-- value must be discounted-->
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="discount_id" type="xs:string" />
    <xs:element name="discount" type="xs:string" />
    <xs:element name="total_price" type="xs:string" />
    <xs:element name="description_txt" type="xs:string" />
    <xs:element name="description" type="xs:string" />

    <!-- Starting of Tags for Contact Section-->
    <xs:element name="contact_details">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="address" />
                <xs:element ref="contact_info" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="location" />
                <xs:element ref="street" />
                <xs:element ref="city" />
                <xs:element ref="postcode" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="location" type="xs:string" />
    <xs:element name="street" type="xs:string" />
    <xs:element name="city" type="xs:string" />
    <xs:element name="postcode" type="xs:string" />

    <xs:element name="contact_info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact_text" />
                <xs:element ref="contact" />
                <xs:element ref="email" />
                <xs:element ref="url" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Ending of Tags for Contact Section-->

    <xs:element name="contact_text" type="xs:string" />
    <xs:element name="contact" type="xs:string" />
    <xs:element name="email" type="xs:string" />
    <xs:element name="url" type="xs:string" />

    <!-- Simple Type Element footer-->
    <xs:element name="footer" type="xs:string" />
</xs:schema>

=== Avinna10/Gift-Store/catalog_20048839.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--
    Name: Avinna Maharjan
    ID: 20048839
    Date: 4/3/2022
-->

<!-- Css External Link -->
<?xml-stylesheet type="text/css" href="catalog_20048839.css"?>

<!-- Root element-->
<Avinna_Store xsi:noNamespaceSchemaLocation="catalog_20048839.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <store id="1001">
        <!-- Store logo and Name-->
        <top>
            <left>
                <logo />
            </left>
            <right>
                <name store_type="physical">Avinna Gift Voucher Store</name>
                <note>Go Cashless</note>
            </right>
        </top>
        <!-- Navigation Bar-->
        <nav>
            <home>Home</home>
            <cards>Gift Cards</cards>
            <contact_us>Contact Us</contact_us>
            <search>Search</search>
        </nav>
    </store>
    <!-- branch element [It repeats multiple times]-->
    <branch branch_id="A10001A" open="10hr/day">        <!-- Open; optional attribute-->
        <!-- Details of branch-->
        <branch_detail>
            <!-- Simplex Type Element-->
            <branch_name>Branch A</branch_name>
            <branch_address>Address: Greenwich, London</branch_address>
            <!-- Complex Type with child element-->
            <branch_contact>
                <mobile_no>Mobile: +44 (0)79 1114 5623</mobile_no>
                <toll_free>Toll Free: 0808 9856742</toll_free>      <!-- optional element-->
                <branch_email>Email: branch_greenwich@ags.co.uk</branch_email>      <!-- optional element-->
            </branch_contact>
        </branch_detail>
        <!-- Voucher Section [Contains the information of different gift vouchers]-->
        <voucher>
            <!-- Here, Gift Vouchers contains the details of the Spotify gift card-->
            <!-- Complex Type with attribute and child element-->
            <gift_vouchers voucher_id="ID1001sP1">
                <!-- Empty Elemeny-->
                <buy/>
                <!-- Simple Type with data string-->
                <buy_txt>Buy</buy_txt>
                <!-- Complex Type with attribute-->
                <voucher_image image_id="spotify" />
                <!-- Complex Type with attribute and data string-->
                <voucher_name serial_no="1234567890">Spotify E-Gift Card</voucher_name>
                <redeem_amount>(&#163;25)</redeem_amount>
                <edition>Limited Edition</edition>      <!-- optional element-->
                <!-- Display contents in tabular format-->
                <table>
                    <!-- Table_row specifies rows of the table
                    It has child elements which holds data of gift card-->
                    <table_row>
                        <!-- Simple type with data string-->
                        <company_txt>Company</company_txt>
                        <type_txt>Type</type_txt>
                    </table_row>
                    <table_row>
                        <!-- Complex Type with attribute and data string-->
                        <company platform="online">Spotify</company>
                        <voucher_type code_no="20AB">Digital</voucher_type> 
                    </table_row>
                    <table_row>
                        <!-- Simple type with data string-->
                        <rating_txt>Rating</rating_txt>
                        <valid_txt>Validity</valid_txt>
                    </table_row>
                    <table_row>
                        <!-- Simple type with data string-->
                        <voucher_rating>4.2</voucher_rating>
                        <!-- Empty Element-->
                        <rating_icon />
                        <!-- COmplex Type with attribute and data string-->
                        <voucher_validity valid="international">1 year</voucher_validity>
                    </table_row>
                    <table_row>
                        <delivery_txt>Delivery</delivery_txt>
                        <return_txt>Return</return_txt>
                    </table_row>
                    <table_row>
                        <delivery delivery_type="online">Online</delivery>
                        <return_policy>Non-returnable</return_policy>
                    </table_row>
                    <table_row>
                        <cost_txt>Price</cost_txt>
                    </table_row>
                    <table_row>
                        <voucher_cost discount_id="discounted">&#163;27</voucher_cost>      <!-- optional attribute discount_id-->
                        <discount>[ 10% off ]</discount>        <!-- optional element-->
                    </table_row>
                    <table_row>
                        <total_price>New Price: &#163;24.3</total_price>        <!-- optional element-->
                    </table_row>
                    <table_row>
                        <description_txt>Description</description_txt>
                    </table_row>
                    <table_row>
                        <description><![CDATA[ Cannot be redeemed for the Spotify Family or Student Plans.]]></description>
                    </table_row>
                </table>
            </gift_vouchers>
            <!-- Here, Gift Vouchers contains the details of the Adidas gift card-->
            <gift_vouchers voucher_id="ID1001aD2">
                <buy/>
                <buy_txt>Buy</buy_txt>
                <voucher_image image_id="adidas" />
                <voucher_name serial_no="9854785478">Adidas Gift Card</voucher_name>
                <redeem_amount>(&#163;50)</redeem_amount>

                <table>
                    <table_row>
                        <company_txt>Company</company_txt>
                        <type_txt>Type</type_txt>
                    </table_row>
                    <table_row>
                        <company platform="shop">Adidas</company>
                        <voucher_type code_no="45AA">Physical</voucher_type>
                    </table_row>
                    <table_row>
                        <rating_txt>Rating</rating_txt>
                        <valid_txt>Validity</valid_txt>
                    </table_row>
                    <table_row>
                        <voucher_rating>4.5</voucher_rating>
                        <rating_icon />
                        <voucher_validity valid="international">1.5 years</voucher_validity>
                    </table_row>
                    <table_row>
                        <delivery_txt>Delivery</delivery_txt>
                        <return_txt>Return</return_txt>
                    </table_row>
                    <table_row>
                        <delivery delivery_type="home_delivery" charge="2">Home</delivery>  <!-- optional attribute charge; shipping charge for home delivery-->
                        <!-- Complex Type with Mixed-->
                        <return_policy>
                            Returnable
                            <return_duration>[Within 5 days of delivery]</return_duration>  <!-- optional element-->
                        </return_policy>
                    </table_row>
                    <table_row>
                        <cost_txt>Price</cost_txt>
                    </table_row>
                    <table_row>
                        <voucher_cost>&#163;54</voucher_cost>
                    </table_row>
                    <table_row>
                        <description_txt>Description</description_txt>
                    </table_row>
                    <table_row>
                        <description><![CDATA[ Can be used to redeem for merchandise on adidas.com and adidas Outlet stores all over the world.]]></description>
                    </table_row>
                </table>
            </gift_vouchers>
        </voucher>
    </branch>
    <branch branch_id="A10001B">
        <branch_detail>
            <branch_name>Branch B</branch_name>
            <branch_address>Address: Holborn, London</branch_address>
            <branch_contact>
                <mobile_no>Mobile: +44 (0)79 1324 5572</mobile_no>
                <branch_email>Email: branch_holborn@ags.co.uk</branch_email>    <!-- optional element-->
            </branch_contact>
        </branch_detail>
        <voucher>
            <!-- Here, Gift Vouchers contains the details of the Argos gift card-->
            <gift_vouchers voucher_id="ID1001aR3">
                <buy/>
                <buy_txt>Buy</buy_txt>
                <voucher_image image_id="argos" />
                <voucher_name serial_no="1109547888">Argos Gift Card</voucher_name>
                <redeem_amount>(&#163;75)</redeem_amount>

                <table>
                    <table_row>
                        <company_txt>Company</company_txt>
                        <type_txt>Type</type_txt>
                    </table_row>
                    <table_row>
                        <company platform="shop">Argos</company>
                        <voucher_type code_no="77CZ">Physical</voucher_type>
                    </table_row>
                    <table_row>
                        <rating_txt>Rating</rating_txt>
                        <valid_txt>Validity</valid_txt>
                    </table_row>
                    <table_row>
                        <voucher_rating>4.1</voucher_rating>
                        <rating_icon />
                        <voucher_validity valid="national">8 months</voucher_validity>
                    </table_row>
                    <table_row>
                        <delivery_txt>Delivery</delivery_txt>
                        <return_txt>Return</return_txt>
                    </table_row>
